/* Auto-generated by m2cgen — DO NOT EDIT MANUALLY
 *
 * Model    : tiny
 * Features : r_amplitude, global_max, global_min, peak_to_peak, q_amplitude, s_amplitude, r_minus_q, r_minus_s, mean, std, energy, skewness, kurtosis, zero_crossing_rate, band_power_0_5hz, band_power_5_15hz, band_power_15_40hz, band_power_40_100hz, dominant_frequency, spectral_centroid, pre_rr_interval, post_rr_interval, rr_ratio, local_rr_mean
 * Trained  : DS1 (de Chazal et al. 2004 inter-patient split)
 * Tested   : DS2 (held-out patients, never seen during training)
 *
 * Usage
 *   double output[N_CLASSES];
 *   score(input_features, output);  // input_features: double[24]
 *   int predicted = argmax(output, N_CLASSES);
 *
 * Compile
 *   arm-none-eabi-gcc -std=c99 -O2 -c ecg_tiny.c -o ecg_tiny.o
 */

#include <string.h>
void score(double * input, double * output) {
    double var0[5];
    if (input[3] <= 4.332919597625732) {
        if (input[18] <= 1.5) {
            if (input[16] <= 0.02514322381466627) {
                if (input[17] <= 0.005766804097220302) {
                    if (input[2] <= -1.3452399969100952) {
                        if (input[20] <= 0.7388888895511627) {
                            memcpy(var0, (double[]){0.015031666499119061, 0.0, 0.984968333500881, 0.0, 0.0}, 5 * sizeof(double));
                        } else {
                            memcpy(var0, (double[]){0.41267847530183804, 0.0, 0.587321524698162, 0.0, 0.0}, 5 * sizeof(double));
                        }
                    } else {
                        if (input[23] <= 0.4322222173213959) {
                            memcpy(var0, (double[]){1.0, 0.0, 0.0, 0.0, 0.0}, 5 * sizeof(double));
                        } else {
                            memcpy(var0, (double[]){1.0, 0.0, 0.0, 0.0, 0.0}, 5 * sizeof(double));
                        }
                    }
                } else {
                    if (input[20] <= 0.5055555701255798) {
                        memcpy(var0, (double[]){0.0, 0.0, 0.0, 1.0, 0.0}, 5 * sizeof(double));
                    } else {
                        if (input[22] <= 0.7988577783107758) {
                            memcpy(var0, (double[]){0.0, 1.0, 0.0, 0.0, 0.0}, 5 * sizeof(double));
                        } else {
                            memcpy(var0, (double[]){1.0, 0.0, 0.0, 0.0, 0.0}, 5 * sizeof(double));
                        }
                    }
                }
            } else {
                if (input[1] <= 2.0315905809402466) {
                    if (input[2] <= -1.5928016304969788) {
                        if (input[0] <= 0.5355771780014038) {
                            memcpy(var0, (double[]){0.0011040703335693897, 0.0, 0.0003514764003048665, 0.0, 0.9985444532661257}, 5 * sizeof(double));
                        } else {
                            memcpy(var0, (double[]){0.5179871250052595, 0.0, 0.48201287499474055, 0.0, 0.0}, 5 * sizeof(double));
                        }
                    } else {
                        if (input[17] <= 0.011654534377157688) {
                            memcpy(var0, (double[]){1.0, 0.0, 0.0, 0.0, 0.0}, 5 * sizeof(double));
                        } else {
                            memcpy(var0, (double[]){0.0, 0.0, 1.0, 0.0, 0.0}, 5 * sizeof(double));
                        }
                    }
                } else {
                    if (input[22] <= 0.5055379569530487) {
                        if (input[1] <= 2.911496162414551) {
                            memcpy(var0, (double[]){0.0, 0.0, 1.0, 0.0, 0.0}, 5 * sizeof(double));
                        } else {
                            memcpy(var0, (double[]){1.0, 0.0, 0.0, 0.0, 0.0}, 5 * sizeof(double));
                        }
                    } else {
                        memcpy(var0, (double[]){1.0, 0.0, 0.0, 0.0, 0.0}, 5 * sizeof(double));
                    }
                }
            }
        } else {
            if (input[4] <= -0.3791859596967697) {
                if (input[6] <= 0.05906754732131958) {
                    if (input[5] <= -1.3265101909637451) {
                        if (input[16] <= 0.05410861223936081) {
                            memcpy(var0, (double[]){0.0, 0.0, 1.0, 0.0, 0.0}, 5 * sizeof(double));
                        } else {
                            memcpy(var0, (double[]){1.0, 0.0, 0.0, 0.0, 0.0}, 5 * sizeof(double));
                        }
                    } else {
                        if (input[3] <= 3.5747694969177246) {
                            memcpy(var0, (double[]){1.0, 0.0, 0.0, 0.0, 0.0}, 5 * sizeof(double));
                        } else {
                            memcpy(var0, (double[]){0.0, 1.0, 0.0, 0.0, 0.0}, 5 * sizeof(double));
                        }
                    }
                } else {
                    if (input[15] <= 0.2460038885474205) {
                        if (input[16] <= 0.011991973035037518) {
                            memcpy(var0, (double[]){0.0, 0.0, 1.0, 0.0, 0.0}, 5 * sizeof(double));
                        } else {
                            memcpy(var0, (double[]){0.0020713828554503743, 0.9394603545805663, 0.058468262563983256, 0.0, 0.0}, 5 * sizeof(double));
                        }
                    } else {
                        if (input[22] <= 1.349646508693695) {
                            memcpy(var0, (double[]){0.3495159412883628, 0.0, 0.6504840587116373, 0.0, 0.0}, 5 * sizeof(double));
                        } else {
                            memcpy(var0, (double[]){0.0177484352224985, 0.0, 0.0, 0.9822515647775015, 0.0}, 5 * sizeof(double));
                        }
                    }
                }
            } else {
                if (input[18] <= 2.5) {
                    if (input[7] <= 3.9854066371917725) {
                        if (input[15] <= 0.5127232223749161) {
                            memcpy(var0, (double[]){0.0006771158440102424, 0.0, 0.9993228841559898, 0.0, 0.0}, 5 * sizeof(double));
                        } else {
                            memcpy(var0, (double[]){1.0, 0.0, 0.0, 0.0, 0.0}, 5 * sizeof(double));
                        }
                    } else {
                        memcpy(var0, (double[]){1.0, 0.0, 0.0, 0.0, 0.0}, 5 * sizeof(double));
                    }
                } else {
                    if (input[22] <= 0.7956896424293518) {
                        if (input[13] <= 5.5) {
                            memcpy(var0, (double[]){0.11031724459286296, 0.0, 0.8896827554071371, 0.0, 0.0}, 5 * sizeof(double));
                        } else {
                            memcpy(var0, (double[]){0.0, 1.0, 0.0, 0.0, 0.0}, 5 * sizeof(double));
                        }
                    } else {
                        if (input[14] <= 0.5402574837207794) {
                            memcpy(var0, (double[]){1.0, 0.0, 0.0, 0.0, 0.0}, 5 * sizeof(double));
                        } else {
                            memcpy(var0, (double[]){0.0, 0.0, 1.0, 0.0, 0.0}, 5 * sizeof(double));
                        }
                    }
                }
            }
        }
    } else {
        if (input[7] <= 5.67227840423584) {
            if (input[22] <= 0.8564382791519165) {
                if (input[2] <= -0.9680898189544678) {
                    if (input[19] <= 16.64474582672119) {
                        if (input[12] <= 11.882091999053955) {
                            memcpy(var0, (double[]){0.004950524910055395, 0.0, 0.9950494750899446, 0.0, 0.0}, 5 * sizeof(double));
                        } else {
                            memcpy(var0, (double[]){0.006976362727823581, 0.0, 0.47823322561390297, 0.5147904116582734, 0.0}, 5 * sizeof(double));
                        }
                    } else {
                        if (input[23] <= 0.8686110973358154) {
                            memcpy(var0, (double[]){0.034385966507513105, 0.09099213496867507, 0.8463591899350565, 0.028262708588755125, 0.0}, 5 * sizeof(double));
                        } else {
                            memcpy(var0, (double[]){0.009181436411098134, 0.7329793416413943, 0.2578392219475075, 0.0, 0.0}, 5 * sizeof(double));
                        }
                    }
                } else {
                    if (input[23] <= 0.6427777707576752) {
                        if (input[20] <= 0.3986111134290695) {
                            memcpy(var0, (double[]){0.1259132093466858, 0.8740867906533142, 0.0, 0.0, 0.0}, 5 * sizeof(double));
                        } else {
                            memcpy(var0, (double[]){1.0, 0.0, 0.0, 0.0, 0.0}, 5 * sizeof(double));
                        }
                    } else {
                        if (input[14] <= 0.3195663094520569) {
                            memcpy(var0, (double[]){1.0, 0.0, 0.0, 0.0, 0.0}, 5 * sizeof(double));
                        } else {
                            memcpy(var0, (double[]){0.026988002972714725, 0.9730119970272852, 0.0, 0.0, 0.0}, 5 * sizeof(double));
                        }
                    }
                }
            } else {
                if (input[2] <= -1.3830559849739075) {
                    if (input[17] <= 0.01651052664965391) {
                        if (input[23] <= 0.5230555534362793) {
                            memcpy(var0, (double[]){0.022392432133311324, 0.8634873577084407, 0.08213919690978738, 0.03198101324846072, 0.0}, 5 * sizeof(double));
                        } else {
                            memcpy(var0, (double[]){0.21467892859735244, 0.07198852000355419, 0.49945361515664993, 0.2138789362424436, 0.0}, 5 * sizeof(double));
                        }
                    } else {
                        if (input[21] <= 0.6041666567325592) {
                            memcpy(var0, (double[]){0.014909272188976593, 0.03132968335846684, 0.012673923848054547, 0.017840514134682503, 0.9232466064698194}, 5 * sizeof(double));
                        } else {
                            memcpy(var0, (double[]){0.9404813549635658, 0.0, 0.0, 0.05951864503643419, 0.0}, 5 * sizeof(double));
                        }
                    }
                } else {
                    if (input[23] <= 0.750555545091629) {
                        if (input[20] <= 0.4902777820825577) {
                            memcpy(var0, (double[]){0.16464332990814617, 0.5818656858930615, 0.25349098419879224, 0.0, 0.0}, 5 * sizeof(double));
                        } else {
                            memcpy(var0, (double[]){0.013629720590768462, 0.004071642971190023, 0.0054059265354905895, 0.9768927099025508, 0.0}, 5 * sizeof(double));
                        }
                    } else {
                        if (input[16] <= 0.024823220446705818) {
                            memcpy(var0, (double[]){0.03421531198439175, 0.0, 0.9657846880156082, 0.0, 0.0}, 5 * sizeof(double));
                        } else {
                            memcpy(var0, (double[]){0.5091647674896683, 0.47128144837543057, 0.01955378413490105, 0.0, 0.0}, 5 * sizeof(double));
                        }
                    }
                }
            }
        } else {
            if (input[20] <= 0.6541666686534882) {
                if (input[14] <= 0.25099341571331024) {
                    if (input[6] <= 6.479251384735107) {
                        if (input[5] <= -1.1393864750862122) {
                            memcpy(var0, (double[]){0.027412578362455694, 0.9685782708713905, 0.004009150766153688, 0.0, 0.0}, 5 * sizeof(double));
                        } else {
                            memcpy(var0, (double[]){0.09411880992389049, 0.0, 0.0, 0.9058811900761095, 0.0}, 5 * sizeof(double));
                        }
                    } else {
                        if (input[22] <= 0.8686639070510864) {
                            memcpy(var0, (double[]){0.014486163639882898, 0.9855138363601171, 0.0, 0.0, 0.0}, 5 * sizeof(double));
                        } else {
                            memcpy(var0, (double[]){0.9184448840855518, 0.038129664583378305, 0.0, 0.043425451331069745, 0.0}, 5 * sizeof(double));
                        }
                    }
                } else {
                    if (input[22] <= 0.891308069229126) {
                        if (input[23] <= 0.5519444644451141) {
                            memcpy(var0, (double[]){0.04676973727302384, 0.07974461650198297, 0.8734856462249931, 0.0, 0.0}, 5 * sizeof(double));
                        } else {
                            memcpy(var0, (double[]){0.04019760063681205, 0.7974375303234174, 0.1457007820146636, 0.01666408702510707, 0.0}, 5 * sizeof(double));
                        }
                    } else {
                        if (input[2] <= -1.736130177974701) {
                            memcpy(var0, (double[]){0.9511752983867582, 0.014895671678616138, 0.0, 0.033929029934625654, 0.0}, 5 * sizeof(double));
                        } else {
                            memcpy(var0, (double[]){0.11029682357419693, 0.02972133402538379, 0.0024663162606421082, 0.8575155261397771, 0.0}, 5 * sizeof(double));
                        }
                    }
                }
            } else {
                if (input[22] <= 0.8929764628410339) {
                    if (input[21] <= 0.7791666686534882) {
                        if (input[17] <= 0.0011427166464272887) {
                            memcpy(var0, (double[]){0.0, 0.0, 0.0, 1.0, 0.0}, 5 * sizeof(double));
                        } else {
                            memcpy(var0, (double[]){1.0, 0.0, 0.0, 0.0, 0.0}, 5 * sizeof(double));
                        }
                    } else {
                        if (input[20] <= 0.840277761220932) {
                            memcpy(var0, (double[]){0.11832781476098071, 0.8595366822523473, 0.02213550298667199, 0.0, 0.0}, 5 * sizeof(double));
                        } else {
                            memcpy(var0, (double[]){0.6687009794774208, 0.2652633036862249, 0.06603571683635431, 0.0, 0.0}, 5 * sizeof(double));
                        }
                    }
                } else {
                    if (input[17] <= 0.0006512904947157949) {
                        if (input[2] <= -0.8586251735687256) {
                            memcpy(var0, (double[]){0.6997307659943691, 0.0, 0.010554547705750652, 0.2897146862998802, 0.0}, 5 * sizeof(double));
                        } else {
                            memcpy(var0, (double[]){0.27605052910962496, 0.723949470890375, 0.0, 0.0, 0.0}, 5 * sizeof(double));
                        }
                    } else {
                        if (input[5] <= -0.6364641189575195) {
                            memcpy(var0, (double[]){0.9722765167427097, 0.017546202193348015, 0.00218401117586156, 0.007993269888080764, 0.0}, 5 * sizeof(double));
                        } else {
                            memcpy(var0, (double[]){0.8149709833916663, 0.03792139538394039, 0.003146768377952815, 0.14396085284644036, 0.0}, 5 * sizeof(double));
                        }
                    }
                }
            }
        }
    }
    memcpy(output, var0, 5 * sizeof(double));
}
